
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pratham
 */
public class front extends javax.swing.JFrame {
Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    public static String us;
    /**
     * Creates new form front
     */
    public front() {
        initComponents();
        conn = dbconnect.connectdb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label6 = new java.awt.Label();
        jPasswordField2 = new javax.swing.JPasswordField();
        button2 = new java.awt.Button();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        button1 = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setMinimumSize(new java.awt.Dimension(1200, 720));
        setName("FRONT"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("AICTE ACTIVITY POINTS MANAGEMENT SYSTEM"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 870, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label4.setBackground(new java.awt.Color(0, 0, 0));
        label4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(0, 204, 204));
        label4.setPreferredSize(new java.awt.Dimension(100, 20));
        label4.setText("Admin Login");
        jPanel2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        label5.setBackground(new java.awt.Color(0, 153, 153));
        label5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label5.setText("Admin_ID");
        jPanel2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        jPanel2.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 90, -1));

        label6.setBackground(new java.awt.Color(0, 153, 153));
        label6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label6.setText("password");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel2.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, -1));

        button2.setBackground(new java.awt.Color(0, 102, 102));
        button2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setLabel("login");
        button2.setMinimumSize(new java.awt.Dimension(50, 25));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel2.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d11.jpg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 250));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 300, 200));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(0, 0, 0));
        label1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 204, 204));
        label1.setText("User Login");
        jPanel3.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        label2.setBackground(new java.awt.Color(0, 153, 153));
        label2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label2.setText("User_ID");
        jPanel3.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        label3.setBackground(new java.awt.Color(0, 153, 153));
        label3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label3.setText("password");
        jPanel3.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel3.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 90, -1));
        jPanel3.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, -1));

        button1.setBackground(new java.awt.Color(0, 102, 102));
        button1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("login");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel3.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 50, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d211.jpg"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 200));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, 300, 200));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Student Registration");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 700, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 1000, 550));

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nn4.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        registration rg = new registration();
        rg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
    if (textField2.getText().trim().isEmpty() && jPasswordField2.getText().trim().isEmpty()) {
            textField2.setText("Enter  Username");
            jPasswordField2.setText("Enter Password");

        } else if (textField2.getText().trim().isEmpty()) {
            textField2.setText("Enter  Username");
        } else if (jPasswordField2.getText().trim().isEmpty()) {
            jPasswordField2.setText("Enter Password");
        } else {  //is  this code kk
            String sql = "select * from admin where ADMIN_ID='" + textField2.getText().trim() + "' and PASSWORD='" + jPasswordField2.getText().trim() + "';";

            try {
                pst = conn.prepareStatement(sql);

                rs = pst.executeQuery();
                if (rs.next()) {
                    rs.close();
                    pst.close();
   
                    Adminblock rg = new Adminblock();
                    rg.setVisible(true);
                    this.setVisible(false);
                    
                    
                   

                } else {
                    JOptionPane.showMessageDialog(null, "incorrect username or password");
                    textField2.setText("");
                    jPasswordField2.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
                // Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } //        catch(Exception e){
            //             JOptionPane.showMessageDialog(null,e);
            finally {
                try {
                    rs.close();
                    pst.close();
                } catch (Exception e) {

                }
            }        // TODO add your handling code here:
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
    if (textField1.getText().trim().isEmpty() && jPasswordField1.getText().trim().isEmpty()) {
            textField1.setText("Enter  Username");
            jPasswordField1.setText("Enter Password");

        } else if (textField1.getText().trim().isEmpty()) {
            textField1.setText("Enter  Username");
        } else if (jPasswordField1.getText().trim().isEmpty()) {
            jPasswordField1.setText("Enter Password");
        } else {  //is  this code kk
            String sql = "select * from student where USN='" + textField1.getText().trim() + "' and PASSWORD='" + jPasswordField1.getText().trim() + "';";

            try {
                pst = conn.prepareStatement(sql);
                us = textField1.getText();

                rs = pst.executeQuery();
                if (rs.next()) {
                    rs.close();
                    pst.close();
                    JOptionPane.showMessageDialog(null, "Login Success!!!");
                    student sp = new student();
                    sp.setVisible(true);
                    this.setVisible(false);
                    
                   

                } else {
                    JOptionPane.showMessageDialog(null, "incorrect username or password");
                    textField1.setText("");
                    jPasswordField1.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
                // Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } //        catch(Exception e){
            //             JOptionPane.showMessageDialog(null,e);
            finally {
                try {
                    rs.close();
                    pst.close();
                } catch (Exception e) {

                }
            }           // TODO add your handling code here:
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("front");
                new front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
